spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    driverClassName: oracle.jdbc.OracleDriver
    username: rm553351
    password: 120303
  jpa:
    hibernate:
      ddl_auto: update